function ex1
    N = 10;
    initial_condition = linspace(0, 1, N + 1);
    %initial_condition = rand(N + 1, 1);

    my_grid = 1 - (2 .^ (5 : -0.5 : 0) - 1) / 31;
    % my_grid = linspace(0, 1, N + 1);

    params = struct( ...
        'u', 1, ...
        'k', 0, ...
        'L', 1, ...
        'initial_condition', initial_condition, ...
        'phi_left', 0, ...
        'phi_right', 1 ...
    );

    method = struct( ...
        'method', 'upwind', ...
        'uniform', false, ...
        'grid', my_grid, ...
        'N', N, ...
        'T', 10, ...
        'dt', 0.1                                                                , ...
        'explicit', true ...
    );

    solution = test(params, method);

    %plot(method.grid, solution(1:30:end, :)', '-*');
    

end