function central_test
    N = 10;
    initial_condition = linspace(0, 1, N + 1);
    initial_condition = rand(N + 1, 1);

    my_grid = 1 - (2 .^ (5 : -0.5 : 0) - 1) / 31;
    % my_grid = linspace(0, 1, N + 1);

    params = struct( ...
        'u', 10, ...
        'k', 1, ...
        'L', 1, ...
        'initial_condition', initial_condition, ...
        'phi_left', 0, ...
        'phi_right', 1 ...
    );

    method = struct( ...
        'method', 'central', ...
        'uniform', false, ...
        'grid', my_grid, ...
        'N', N, ...
        'T', 0.1, ...
        'dt', 0.0001, ...
        'explicit', false ...
    );

    solution = central(params, method);

    plot(method.grid, solution(1 : 30 : end, :)', '-*');
end