function ex1
    N = 10;
    my_grid = 1 - (2 .^ (linspace(5, 0, N + 1)) - 1) / 31;
    initial_condition = my_grid; % g(x) = x as initial condition

    params = struct( ...
        'u', 10, ...
        'k', 1, ...
        'L', 1, ...
        'initial_condition', initial_condition, ...
        'phi_left', 0, ...
        'phi_right', 1 ...
    );

    method = struct( ...
        'method', 'central', ...
        'uniform', false, ...
        'grid', my_grid, ...
        'N', N, ...
        'T', 0.1, ...
        'dt', 0.001, ...
        'explicit', false ...
    );

    solution = unsteady_conv_diff(params, method);
    
    surf(method.grid, 0 : method.dt : method.T, solution)
    xlabel('x');
    ylabel('t');
    zlabel('y');
end